# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "199da1c13af6b18f12b15556b535319b"
application_url = "https://finds-briefs-tap-focused.trycloudflare.com"
embedded = true
name = "kursa-darba-app"
handle = "kursa-darba-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://finds-briefs-tap-focused.trycloudflare.com/auth/callback",
  "https://finds-briefs-tap-focused.trycloudflare.com/auth/shopify/callback",
  "https://finds-briefs-tap-focused.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "kursa-darba-store-1.myshopify.com"
automatically_update_urls_on_dev = true
